ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS remember_token VARCHAR(255);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tipo_suscripcion VARCHAR(50) DEFAULT 'free';
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS google_id VARCHAR(255);
